name: 'Terraform-apply'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PAT: ${{secrets.PAT}}
  MY_EC2_KEY: ${{secrets.MY_EC2_KEY}}

jobs:    
  manual-approval:
    name: manual approval
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      contents: read

    steps: 
      - name: Await for manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{github.TOKEN}}
          approvers: FaZ3r
          minimum-approvals: 1
          issue-title: "Deploy infrastructure to AWS"
          issue-body: "Please approve or deny the deployment of the latest version"
          fail-on-denial: true
          exclude-workflow-initiator-as-approver: false


  terraform-apply:
    name: 'terraform-apply'
    runs-on: ubuntu-latest
    environment: production
    needs: manual-approval

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest
        cli_config_credentials_token: ${{env.PAT}}

    - name: Terraform Init
      run: terraform init

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
        aws-region: eu-west-2
        
    - name: Copy SSH key for Packer
      run: | 
        echo ${{env.MY_EC2_KEY}} > ~/my_key.pem
        chmod 600 ~/my_key.pem

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
